### The root api endpoint
GET http://127.0.0.1:8000/ HTTP/1.1
Content-Type: application/json

### The endpoint to get all the posts
GET http://127.0.0.1:8000/posts HTTP/1.1
Content-Type: application/json

### The SQL query to get a specific post
GET http://127.0.0.1:8000/posts/3 HTTP/1.1

### The post endpoint that creates posts
POST http://127.0.0.1:8000/posts HTTP/1.1
Content-Type: application/json

{
    "title": "Audioslave",
    "content": "Like a stone",
    "published": "true"
}