version: "3.9"
services:
  api:
    build: kennedy_mungai/simple_social_backend
    depends_on:
      - mysql
    ports:
      - 8000:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Password1!
      - MYSQL_DATABASE=simple_social_db
      - MYSQL_USER=root
    volumes:
      - simple_social_db=/var/lib/mysql/simple_social_db

volumes:
  simple_social_db: